name: absence_kasau_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  calendar_timeline_sbk: ^1.1.7

  # State Management
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.2.2

  # ML Kit (langsung gunakan ini, jangan tambahkan commons manual!)
  google_mlkit_face_detection: ^0.13.1

  # Camera & Image
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.2.0

  # Location & Maps
  geolocator: ^13.0.2
  location: ^7.0.0
  google_maps_flutter: ^2.7.0
  detect_fake_location: ^2.3.0

  # QR / Barcode
  mobile_scanner: ^5.2.3

  # Storage / Preferences
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1

  # TensorFlow Lite
  tflite_flutter: ^0.11.0

  # HTTP
  http: ^1.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  flutter_gen_runner: ^5.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true